#项目使用项配置
#projectType仅支持web、app、api
projectType: web
project: rewardbase
browser: chrome_x86_v81
threadCount: 1

#***************************** 项目配置 **************************************
#  web项目配置示例
rewardbase:
  url: https://www.baidu.com
  normalUser:
    username: admin
    password: admin123
  dbinfo:
    type: mysql        #数据库类型,mysql/oracle/hive/sqlite3
  timeout: 30

rewardbase2:
  url: https://www.baidu.com
  normalUser:
    username: admin
    password: admin123
  dbinfo:
    type: mysql        #数据库类型,mysql/oracle/hive/sqlite3
  timeout: 30

# APK配置示例
appOperateInfo:
  appInfo:
    appName: baidu.apk
    appActivity: com.baidu.searchbox.MainActivity
    appPackage: com.baidu.searchbox
  useDevice: device1
  normalUser:
    username: admin
    password: admin123
  dbinfo:
    type: oracle        #数据库类型



#***************************** 数据库配置 *************************************
mysql:
  jdbcClass: com.mysql.cj.jdbc.Driver
  jdbcurl: jdbc:mysql://127.0.0.1:3306/autoadmin?serverTimezone=UTC
  username: autoadmin
  password: Zwx232372

oracle:
  jdbcClass: oracle.jdbc.driver.OracleDriver
  jdbcurl: jdbc:oracle:thin:@localhost:1521:yfbceg
  username: autoadmin
  password: Zwx232372

sqlite3:
  jdbcClass: org.sqlite.JDBC
#  jdbcurl: jdbc:sqlite:D:\01_Devspace\python\autotest\autotest\db.sqlite3
  jdbcurl: jdbc:sqlite:/mnt/wind/01_Devspace/python/autotest/autotest/db.sqlite3
  username:
  password:


#***************************** 浏览器驱动配置 *************************************
webbrowser:
  chrome_x86_v81: chromedriver.exe
  #  分布式场景暂不支持firefox
  firefox_x64: geckodriver-v0.26.0-win64.exe
  ie_x86: IEDriverServer_Win32_3.150.1.exe
  ie_x64: IEDriverServer_x64_3.150.1.exe
  #  分布式的情况下官方暂未支持edge
  edge_v81: msedgedriver_81.exe


#***************************** 安卓设备信息配置 *************************************
device1:
  deviceName: 7396257f
  platformVersion: 9
device2:
  deviceName: emulator-5554
  platformVersion: 7.1.2


#***************************** APPIUM配置 *************************************
appium_config:
  automationName: uiautomator2
  platformName: android
  newCommandTimeout: 60
  autoWebview: false
  noReset: true
#  fullReset: true
  printPageSourceOnFindFailure: true
  clearSystemFiles: true
  appWaitDuration: 20000
#  adbport指定了容易有问题
#  adbPort: 9000
  autoWebviewTimeout: 2000
  unicodeKeyboard: true
  resetKeyboard: true
  #  set browsername
  #  Name of mobile web browser to automate. Should be an empty string if automating an app instead. 'Safari' for iOS and 'Chrome', 'Chromium', or 'Browser' for Android
#  browserName: Chrome

seleniumGrid:
  switch: False
  hubUrl: http://192.168.3.13:31361/wd/hub
  uploadDir: dir
  download: dir
