#appInfo:
#  app: D:/01_Devspace/python\workspace/framework/apk/imooc7.2.310102001android.apk
#  appActivity: com.imooc.component.imoocmain.index.MCMainActivity
#  appPackage: cn.com.open.mooc

appInfo:
  app: D:/01_Devspace/python\workspace/framework/apk/baidu.apk
  appActivity: com.baidu.searchbox.MainActivity
  appPackage: com.baidu.searchbox

appium_config:
  automationName: uiautomator2
  platformName: android
  newCommandTimeout: 60
  autoWebview: false
  noReset: true
#  fullReset: true
  printPageSourceOnFindFailure: true
  clearSystemFiles: true
  appWaitDuration: 20000
#  adbport指定了容易有问题
#  adbPort: 9000
  autoWebviewTimeout: 2000
  unicodeKeyboard: true
  resetKeyboard: true
  #  set browsername
  #  Name of mobile web browser to automate. Should be an empty string if automating an app instead. 'Safari' for iOS and 'Chrome', 'Chromium', or 'Browser' for Android
#  browserName: Chrome

# only support on device avaliable
device:
  device1:
    available: true
    deviceName: 7396257f
    platformVersion: 9
  device2:
    available: false
    deviceName: emulator-5554
    platformVersion: 7.1.2



remoteurl: http://localhost:4723/wd/hub

